alternate: Usagi no Niku
darkmode: false

homeConfig:
  fixedCover: "https://ooo.0x0.ooo/2024/06/04/OJcAFG.jpg"

social:
  github: https://github.com/TrueRou || github || "#191717"
  email: mailto:TrueRou@outlook.com || envelope || "#55acd5"

widgets:
  random_posts: false
  recent_comments: false

footer:
  since: 2023
  count: true
  icp:
    enable: true
    icon: ""
    icpnumber: "吉ICP备2024011374号"
    beian: ""
    recordcode: ""
post:
  count: true

seo:
  bing: 0B3F16A91C828F47E4FA05BA9A9D465E
  google: HVbd_neHe-ZPmmR_IUzIfLkUgw0aC0gV_H4GvFy6m24
  baidu: baea07cdd156d06fbf27702460bf3804

modules:
  unlazyHash: true
  visibilityListener: false

loader:
  start: false

menu:
  home: / || home
  posts:
    default: / || feather
    categories: /categories/ || th
    tags: /tags/ || tags
    archives: /archives/ || list-alt 
  about: /about/ || user
  friends: /friends/ || heart

reward:
  enable: false

vendors:
  css:
    fancybox: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css