alternate: Usagi no Niku
darkmode: false

homeConfig:
  fixedCover: "https://ooo.0x0.ooo/2024/06/04/OJcAFG.jpg"

social:
  github: https://github.com/TrueRou || github || "#191717"
  email: mailto:TrueRou@outlook.com || envelope || "#55acd5"

widgets:
  random_posts: false
  recent_comments: false

font:
  enable: true
  # 从google字体库加载,如果自定义@font-face请关闭
  loadFromGoogle: true
  # 字体选项:
  # `external`:从google字体库加载字体.
  # `family: 字体家族名,无需引号
  # `size: x.x`. 以`em`为单位. 默认: 1 (16px)

  # 适用于所有在body标签内的文字.
  global:
    external: true
    family: Mulish
    size:

  # 大标题字体.
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # 页面标题字体.
  title:
    external: true
    family:
    size: 2.5

  # 标题字体.
  headings:
    external: true
    family:
    size:

  # 文章字体.
  posts:
    external: false
    family:

  # 代码块的字体
  codes:
    external: true
    family: Inconsolata

footer:
  since: 2023
  count: true
  icp:
    enable: true
    icon: ""
    icpnumber: "吉ICP备2024011374号"
    beian: ""
    recordcode: ""
post:
  count: true

seo:
  bing: 0B3F16A91C828F47E4FA05BA9A9D465E
  google: HVbd_neHe-ZPmmR_IUzIfLkUgw0aC0gV_H4GvFy6m24
  baidu: baea07cdd156d06fbf27702460bf3804

modules:
  unlazyHash: true
  visibilityListener: false

loader:
  start: false

menu:
  home: / || home
  posts:
    default: / || feather
    categories: /categories/ || th
    tags: /tags/ || tags
    archives: /archives/ || list-alt
  about: /about/ || user
  friends: /friends/ || heart

reward:
  enable: false
